2016-04-21 12:58:05,740 (3169/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/local/Cellar/pgcli/0.20.1/libexec/lib/python2.7/site-packages/pgcli/main.py", line 235, in connect\n    raise e\nOperationalError: could not connect to server: No such file or directory\n\tIs the server running locally and accepting\n\tconnections on Unix domain socket "/tmp/.s.PGSQL.5432"?\n\n'
2016-05-03 10:29:04,649 (26112/MainThread) pgcli.pgexecute ERROR - sql: u"SELECT pg_terminate_backend(pg_stat_activity.pid)FROM pg_stat_activityWHERE pg_stat_activity.datname = 'TARGET_DB'", error: ProgrammingError('syntax error at or near "."\nLINE 1: ...ty.pid)FROM pg_stat_activityWHERE pg_stat_activity.datname =...\n                                                             ^\n',)
2016-05-03 10:29:04,650 (26112/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/local/Cellar/pgcli/0.20.1/libexec/lib/python2.7/site-packages/pgcli/pgexecute.py", line 266, in run\n    yield self.execute_normal_sql(sql) + (sql, True)\n  File "/usr/local/Cellar/pgcli/0.20.1/libexec/lib/python2.7/site-packages/pgcli/pgexecute.py", line 286, in execute_normal_sql\n    cur.execute(split_sql)\nProgrammingError: syntax error at or near "."\nLINE 1: ...ty.pid)FROM pg_stat_activityWHERE pg_stat_activity.datname =...\n                                                             ^\n\n'
2016-05-03 10:29:07,278 (26112/MainThread) pgcli.pgexecute ERROR - sql: u"SELECT pg_terminate_backend(pg_stat_activity.pid)FROM pg_stat_activityWHERE pg_stat_activity.datname = 'TARGET_DB'", error: ProgrammingError('syntax error at or near "."\nLINE 1: ...ty.pid)FROM pg_stat_activityWHERE pg_stat_activity.datname =...\n                                                             ^\n',)
2016-05-03 10:29:07,278 (26112/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/local/Cellar/pgcli/0.20.1/libexec/lib/python2.7/site-packages/pgcli/pgexecute.py", line 266, in run\n    yield self.execute_normal_sql(sql) + (sql, True)\n  File "/usr/local/Cellar/pgcli/0.20.1/libexec/lib/python2.7/site-packages/pgcli/pgexecute.py", line 286, in execute_normal_sql\n    cur.execute(split_sql)\nProgrammingError: syntax error at or near "."\nLINE 1: ...ty.pid)FROM pg_stat_activityWHERE pg_stat_activity.datname =...\n                                                             ^\n\n'
2016-05-03 10:29:20,406 (26112/MainThread) pgcli.pgexecute ERROR - sql: u"SELECT pg_terminate_backend(pg_stat_activity.pid)FROM pg_stat_activityWHERE pg_stat_activity.datname = 'TARGET_DB'", error: ProgrammingError('syntax error at or near "."\nLINE 1: ...ty.pid)FROM pg_stat_activityWHERE pg_stat_activity.datname =...\n                                                             ^\n',)
2016-05-03 10:29:20,407 (26112/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/local/Cellar/pgcli/0.20.1/libexec/lib/python2.7/site-packages/pgcli/pgexecute.py", line 266, in run\n    yield self.execute_normal_sql(sql) + (sql, True)\n  File "/usr/local/Cellar/pgcli/0.20.1/libexec/lib/python2.7/site-packages/pgcli/pgexecute.py", line 286, in execute_normal_sql\n    cur.execute(split_sql)\nProgrammingError: syntax error at or near "."\nLINE 1: ...ty.pid)FROM pg_stat_activityWHERE pg_stat_activity.datname =...\n                                                             ^\n\n'
2016-05-03 10:29:38,659 (26112/MainThread) pgcli.pgexecute ERROR - sql: u'pg_stat_activity', error: ProgrammingError('syntax error at or near "pg_stat_activity"\nLINE 1: pg_stat_activity\n        ^\n',)
2016-05-03 10:29:38,660 (26112/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/local/Cellar/pgcli/0.20.1/libexec/lib/python2.7/site-packages/pgcli/pgexecute.py", line 266, in run\n    yield self.execute_normal_sql(sql) + (sql, True)\n  File "/usr/local/Cellar/pgcli/0.20.1/libexec/lib/python2.7/site-packages/pgcli/pgexecute.py", line 286, in execute_normal_sql\n    cur.execute(split_sql)\nProgrammingError: syntax error at or near "pg_stat_activity"\nLINE 1: pg_stat_activity\n        ^\n\n'
